version: '3.7'

services:
  db:
    container_name: database-react
    image: postgres
    volumes:
      - .docker/db:/var/lib/postgresql/data
      
  ruby:
    container_name: ruby-api-react
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./api:/webapp
    labels:
      - "traefik.frontend.rule=Host:api.myproject.test"
      - "traefik.port=3000"
    depends_on:
          - db

  client:
   build: './client'
   volumes:
     - './client:/home/node/app:rw,consistent'
   working_dir: '/home/node/app'
   environment: 
     JWT_SECRET: "MyBestSecret"
   command: 'yarn start'
   ports:
     - 127.0.0.1:3001:3002

  traefik:
    container_name: traefik-react
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    labels:
      - "traefik.frontend.rule=Host:traefik.myproject.test"
      - "traefik.port=7000"
